### ISSUE TITLE
Sass Variables

### ISSUE THREAD

**Issue by mlatimetoact** [csstools/stylelint-media-use-custom-media#1]
I am using sass in my project and like to use sass variables in my media queries.
Can you add an option to switch from css variable to sass variables.

My code will look something like that:

@media ($sm) {}
@media ($sm), ($md) {}
@media screen and ($sm) {}

**Comment by jonathantneal** [comment]
That sounds like a reasonable idea for a different plugin, as this one relies on the standards-tracking [Custom Media Queries specification](https://drafts.csswg.org/mediaqueries-5/#custom-mq). Would you have any interest in building one? How would we handle detecting whether or not a Sass variable was correctly available, or would we? I could provide guidance, but I do not presently have the time to build this.
